### ISSUE TITLE
Roadmap to stable

### ISSUE THREAD

**Issue by imcyee** [imcyee/superstream#1]
TODO:

- [x] Support any type of id (now only support integer, and kinda problematic for string id)
- [X] sorted set support of integer rank
- [ ] Port: python -> ts
  - [ ] aggregate
  - [X] Direct translate
  - [ ] Test
  - [ ] Cassandra
  - [X] Redis

- [ ] Port manager

RoadMap

- [x]  Better id generator (done with uuidv1)
Currently serializationId can be collided if two activity with same verb and object can be collided if both were generated at the same time.
Spec (Not lock and open for changes):
  - No collision,
  - must be sortable, it is used by database to query, should fit for both redis or cassandra. 
  - final has to be int (for querying purposes)

- [ ]  Better test coverage:
  - unit test for important component such as feed, activity, aggregate
 
- [x]  Better e2e test: (testContainers: redis and cassandra for managers)
  - integration test with database: cassandra and redis
- [ ] Add server support which user can spin up a docker
- [ ] Add `rehydration` guide on how to rehydra activity that acquire from feed.
- [ ] myrocks

Except the changes specified at [What is different](#What is different), if the code doesn't seems right to you, you can always refer back to the [source code](https://github.com/tschellenbach/Stream-Framework)
